SST/Models/Flavor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SST.Models
{
  public class Flavor
  {
    public int FlavorId { get; set; }
    
    [Required(ErrorMessage = "Creating a flavor requires a name")]
    public string Name { get; set; }
    
    public List<FlavorTreat> JoinEntities { get;}
  }
}

SST/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using SST.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SST.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly SSTContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, SSTContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> flavors = _db.Flavors.ToList();
      return View(flavors);
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View();
    }

    [Authorize]
    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
                                .Include(flavor => flavor.JoinEntities)
                                .ThenInclude(join => join.Treat)
                                .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize]
    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }

    [Authorize]
    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(p => p.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [Authorize]
    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
      #nullable disable
      if (joinEntity == null && treatId != 0)
      {
          _db.FlavorTreats.Add(new FlavorTreat() { 
              TreatId = treatId, FlavorId = flavor.FlavorId
          });
          _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntity = _db.FlavorTreats.FirstOrDefault(joinEntity => joinEntity.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntity);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = joinEntity.FlavorId});
    }
  }
}

SST/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using SST.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SST.Controllers
{
  public class TreatsController : Controller
  {
    private readonly SSTContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, SSTContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      List<Treat> treats = _db.Treats.ToList();
      return View(treats);
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View();
    }

    [Authorize]
    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }
    
    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
                                .Include(treat => treat.JoinEntities)
                                .ThenInclude(join => join.Flavor)
                                .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    [Authorize]
    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize]
    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(p => p.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View(thisTreat);
    }

    [Authorize]
    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
      #nullable disable
      if (joinEntity == null && flavorId != 0)
      {
          _db.FlavorTreats.Add(new FlavorTreat() { 
              FlavorId = flavorId, TreatId = treat.TreatId
          });
          _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntity = _db.FlavorTreats.FirstOrDefault(joinEntity => joinEntity.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntity);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = joinEntity.TreatId});
    }
  }
}

SST/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model SST.Models.Flavor;
@using SST.Models;

<div class="main-container">
  <h2>Flavors</h2>
  <hr/>

  <p>Add a treat to: @Html.DisplayFor(model => model.Name)</p>

  @if (((SelectList)ViewBag.TreatId).Count() == 0)
  {
    <p>No treats have been added yet!</p>
    <p> Start with @Html.ActionLink("Adding a treat", "Create", "Treats")</p>
  }
  else
  {
    @using (Html.BeginForm("AddTreat", "Flavors"))
    {
      @Html.HiddenFor(model => model.FlavorId)

      @Html.Label("Select a treat")
      @Html.DropDownList("TreatId")

      <input type="submit" value="Save" />    
    }
  }

  <div class="btm-bar">
    @Html.ActionLink("Back to Flavors", "Index")
  </div>
</div>

SST/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model SST.Models.Flavor;
@using SST.Models;

<div class="main-container">
  <h2>Flavors</h2>
  <hr/>
  <h4>Add a new flavor</h4>
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    <input type="submit" value="Add new Flavor" />
  }
</div>

SST/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SST.Models.Flavor;

<div class="main-container">
  
  <h2>Delete Flavor:</h2>
  <hr/>
  <h3>Are you sure you want to delete this flavor?</h3>

  @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete flavor" />
  }
  @Html.ActionLink("Back to flavor's List", "Index")
</div>

SST/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model SST.Models.Flavor;
@using SST.Models
@using System.Collections.Generic;
@using System.Security.Claims;

<div class="main-container">

  <h2>Flavor Details:</h2>
  <hr/>
  <h3>@Html.DisplayFor(model => model.Name)</h3>

  @if(@Model.JoinEntities.Count == 0)
  {
    <p>You can't find @Html.DisplayFor(model => model.Name) at this moment in our shop.</p>

    @if (User.Identity.IsAuthenticated)
    {
      <p>@Html.ActionLink("Add Treat", "AddTreat", new { id = Model.FlavorId })</p>
    }
  }
  else
  {
    <p>You can find @Html.DisplayFor(model => model.Name) in the following:</p>
    <ol>
      @foreach(FlavorTreat join in Model.JoinEntities)
      {
        <div class="siblings">
          <li>@Html.ActionLink($"{@join.Treat.Name}", "Details", "Treats", new { id = @join.TreatId })</li>
          @using (Html.BeginForm("DeleteJoin", "Treats"))
          {
            @Html.Hidden("joinId", join.FlavorTreatId)
            <input type="submit" value="Remove Treat"/>
          }
        </div>
      }
    </ol>
  }

@if (User.Identity.IsAuthenticated)
{
<hr/>
  <div class="btm-bar">
    @Html.ActionLink("Add treat with this flavor", "AddTreat", new { id = Model.FlavorId })
    @Html.ActionLink("Edit flavor", "Edit", new { id = Model.FlavorId })
    @Html.ActionLink("Delete this flavor", "Delete", new { id = Model.FlavorId })
  </div>
}
<hr/>
  <div class="btm-bar">
    @Html.ActionLink("Back to Flavors", "Index")
    @Html.ActionLink("Check out Treats", "Index", "Treats")
  </div>

</div>

SST/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SST.Models.Flavor

<div class="main-container">
  
  <h2>Edit flavor:</h2>
  <hr/>

  <h3>Edit: @Html.DisplayFor(model => model.Name)</h3>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save Changes" />
  }

    <div class="btm-bar">
    @Html.ActionLink("Add treat to this treat", "AddTreat", new { id = Model.FlavorId })
  </div>
</div>

SST/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using SST.Models;

<div class="main-container">
  <h2>Flavors</h2>
  <hr/>

  @if (@Model.Count == 0)
  {
    <h3>No flavors have been added yet!</h3>
    @Html.ActionLink("Add a treat", "Create", "Treats")
  }
  else
  {
    <ol>
      @foreach (Flavor flavor in Model)
      {
        <li>@Html.ActionLink($"{flavor.Name}", "Details", new { id = flavor.FlavorId })</li>
      }
    </ol>
  }

</div>

@if (User.Identity.IsAuthenticated)
{
  <div class="btm-bar">
    @Html.ActionLink("Add a flavor", "Create")
  </div>
}